apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: dev
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: glanceman/webimage
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-webservice
  namespace: dev
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
      port: 3000
      targetPort: 3000
      nodePort: 80